import {template01} from '/v8/templates/01-ip-only.js?v=8.0.0-alpha2';

const $=s=>document.querySelector(s);const canvas=$('#canvas');const inspector=$('#inspector');const saveState=$('#saveState');const toastEl=$('#toast');
let state=structuredClone(template01.defaults);let preview=false;let selected=null;let history=[];let future=[];let saveTimer=null;document.documentElement.dataset.studio='v8-alpha2';
try{const saved=localStorage.getItem('onlyevent-studio-v8:01');if(saved)state={...state,...JSON.parse(saved)}}catch{}

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.classList.remove('show'),1400)}
function checkpoint(){history.push(JSON.stringify(state));if(history.length>60)history.shift();future.length=0;syncHistory()}
function syncHistory(){$('#undoBtn').disabled=!history.length;$('#redoBtn').disabled=!future.length}
function scheduleSave(){saveState.textContent='保存中…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem('onlyevent-studio-v8:01',JSON.stringify(state));saveState.textContent='已保存'},220)}
function setDeep(path,value){const a=path.split('.');let o=state;for(let i=0;i<a.length-1;i++){const k=/^\d+$/.test(a[i])?Number(a[i]):a[i];o=o[k]}const last=/^\d+$/.test(a.at(-1))?Number(a.at(-1)):a.at(-1);o[last]=value;scheduleSave()}
function getDeep(path){return path.split('.').reduce((o,k)=>o?.[/^\d+$/.test(k)?Number(k):k],state)}

function siteHtml(){return `<div class="oe-site oe-editing" style="--primary:${esc(state.theme)}">
<div class="oe-topbar"><div class="oe-wrap"><span>${esc(state.date)} · ${esc(state.location)}</span><span>QQ群 · 微信群 · B站</span></div></div>
<header class="oe-nav"><div class="oe-wrap"><a class="oe-brand"><i>OE</i><span data-edit="eventName" contenteditable="true">${esc(state.eventName)}</span></a><nav class="oe-links"><a href="#tickets">票务</a><a href="#highlights">企划</a><a href="#booths">摊位</a><a href="#stage">日程</a></nav></div></header>
<section class="oe-hero" id="hero" data-section="hero"><div class="oe-wrap oe-hero-grid"><div class="oe-copy"><div class="oe-ey">IP ONLY / FAN EVENT</div><h1><span data-edit="eventName" contenteditable="true">${esc(state.eventName)}</span><br><em>ONLY</em></h1><p data-edit="tagline" contenteditable="true">${esc(state.tagline)}</p><div class="oe-meta"><span class="oe-pill" data-edit="date" contenteditable="true">${esc(state.date)}</span><span class="oe-pill" data-edit="location" contenteditable="true">${esc(state.location)}</span></div></div><div class="oe-art"><div class="oe-kv" data-image="heroImage" style="background-image:linear-gradient(180deg,transparent,#0004),url('${esc(state.heroImage)}')"></div><div class="oe-sticker oe-s1">限定企划 ✦</div><div class="oe-sticker oe-s2">40+ 社团</div><div class="oe-sticker oe-s3">COS OK!</div></div></div></section>
<div class="oe-ribbon">摊位公开中 ✦ 特典票限量 ✦ COS 自由行开放 ✦ 舞台企划更新</div>
<section class="oe-section alt" id="tickets" data-section="tickets"><div class="oe-wrap"><div class="oe-head"><h2>票种与特典</h2><span>第三方售票</span></div><div class="oe-grid" id="ticketList">${state.tickets.map((x,i)=>ticketHtml(x,i)).join('')}<button class="oe-add" data-add="tickets" type="button">＋ 添加票种</button></div></div></section>
<section class="oe-section" id="highlights" data-section="highlights"><div class="oe-wrap"><div class="oe-head"><h2>本届特别企划</h2><span>SECTION 01</span></div><div class="oe-specials" id="highlightList">${state.highlights.map((x,i)=>highlightHtml(x,i)).join('')}<button class="oe-add" data-add="highlights" type="button">＋ 添加企划</button></div></div></section>
<section class="oe-section alt" id="booths" data-section="booths"><div class="oe-wrap"><div class="oe-head"><h2>摊位与场地图</h2><span>SECTION 02</span></div><div class="oe-booth-layout"><div class="oe-map"></div><div class="oe-list" id="boothList">${state.booths.map((x,i)=>boothHtml(x,i)).join('')}<button class="oe-add" data-add="booths" type="button">＋ 添加摊位</button></div></div></div></section>
<section class="oe-section" id="stage" data-section="stage"><div class="oe-wrap"><div class="oe-head"><h2>舞台 / 当天日程</h2><span>SECTION 03</span></div><div id="scheduleList">${state.schedule.map((x,i)=>scheduleHtml(x,i)).join('')}<button class="oe-add" data-add="schedule" type="button">＋ 添加日程</button></div></div></section>
<section class="oe-section alt" id="community" data-section="community"><div class="oe-wrap"><div class="oe-head"><h2>社群与活动公告</h2><span>SECTION 04</span></div><div class="oe-community"><article><b>QQ群</b><p>群号：123456789</p></article><article><b>微信群</b><p>现场通知与临时公告。</p></article><article><b>B站</b><p>PV、嘉宾公开、节目预告。</p></article><article><b>小红书</b><p>返图、攻略与摊位推荐。</p></article></div></div></section>
<footer class="oe-footer"><div class="oe-wrap"><h2>${esc(state.eventName)}</h2><p>OnlyEvent Studio · 模板负责设计，主办方负责内容。</p></div></footer></div>`}
function ticketHtml(x,i){return `<article class="oe-card" data-item="tickets.${i}"><h3 data-edit="tickets.${i}.name" contenteditable="true">${esc(x.name)}</h3><div class="oe-price" data-edit="tickets.${i}.price" contenteditable="true">${esc(x.price)}</div><p data-edit="tickets.${i}.gift" contenteditable="true">${esc(x.gift)}</p></article>`}
function highlightHtml(x,i){return `<article class="oe-special" data-item="highlights.${i}"><h3 data-edit="highlights.${i}.title" contenteditable="true">${esc(x.title)}</h3><p data-edit="highlights.${i}.text" contenteditable="true">${esc(x.text)}</p></article>`}
function boothHtml(x,i){return `<article class="oe-card" data-item="booths.${i}"><small data-edit="booths.${i}.no" contenteditable="true">${esc(x.no)}</small><h3 data-edit="booths.${i}.name" contenteditable="true">${esc(x.name)}</h3><p data-edit="booths.${i}.type" contenteditable="true">${esc(x.type)}</p></article>`}
function scheduleHtml(x,i){return `<div class="oe-event" data-item="schedule.${i}"><span data-edit="schedule.${i}.time" contenteditable="true">${esc(x.time)}</span><b data-edit="schedule.${i}.title" contenteditable="true">${esc(x.title)}</b><span data-edit="schedule.${i}.stage" contenteditable="true">${esc(x.stage)}</span></div>`}
function mount(){canvas.innerHTML=siteHtml();bindCanvas();syncPreviewClass()}
function syncPreviewClass(){canvas.classList.toggle('preview',preview);canvas.querySelectorAll('[contenteditable]').forEach(el=>el.contentEditable=preview?'false':'true')}
function bindCanvas(){canvas.addEventListener('input',onInput);canvas.addEventListener('click',onClick);canvas.addEventListener('focusin',onFocus,true)}
function onInput(e){const el=e.target.closest('[data-edit]');if(!el||preview)return;setDeep(el.dataset.edit,el.textContent)}
function onFocus(e){const el=e.target.closest('[data-edit]');if(!el||preview)return;selected={kind:'field',path:el.dataset.edit};openFieldInspector(el.dataset.edit)}
function onClick(e){if(preview)return;const img=e.target.closest('[data-image]');if(img){selected={kind:'image',path:img.dataset.image};openImageInspector(img.dataset.image);return}const add=e.target.closest('[data-add]');if(add){addItem(add.dataset.add,add);return}const item=e.target.closest('[data-item]');if(item&&!e.target.closest('[data-edit]')){selected={kind:'item',path:item.dataset.item};openItemInspector(item.dataset.item);return}const sec=e.target.closest('[data-section]');if(sec&&!e.target.closest('[data-edit]'))openSectionInspector(sec.dataset.section)}
function openFieldInspector(path){const value=getDeep(path);inspector.innerHTML=`<h3>编辑内容</h3><label>内容<textarea id="fieldInput">${esc(value)}</textarea></label><p class="hint">也可以直接在画布里输入，不会刷新页面。</p>`;$('#fieldInput').addEventListener('input',e=>{checkpoint();setDeep(path,e.target.value);canvas.querySelectorAll(`[data-edit="${CSS.escape(path)}"]`).forEach(x=>x.textContent=e.target.value)})}
function openImageInspector(path){inspector.innerHTML=`<h3>图片</h3><p>当前：${esc(path)}</p><div class="row"><button id="replaceImage" type="button">替换图片</button></div><p class="hint">替换后只修改当前图片节点，不重建整页。</p>`;$('#replaceImage').onclick=()=>{$('#imageInput').dataset.path=path;$('#imageInput').click()}}
function openItemInspector(path){const [root,idxStr]=path.split('.');const i=Number(idxStr);inspector.innerHTML=`<h3>条目</h3><p>${esc(path)}</p><div class="row"><button id="dupItem" type="button">复制</button><button id="upItem" type="button">上移</button><button id="downItem" type="button">下移</button><button id="delItem" class="danger" type="button">删除</button></div>`;$('#dupItem').onclick=()=>duplicateItem(root,i);$('#upItem').onclick=()=>moveItem(root,i,-1);$('#downItem').onclick=()=>moveItem(root,i,1);$('#delItem').onclick=()=>deleteItem(root,i)}
function openSectionInspector(key){inspector.innerHTML=`<h3>模块</h3><p>${esc(key)}</p><p class="hint">模板负责布局；这里只放该模块真正需要的内容设置。</p>`}
function addItem(root,button){checkpoint();let item;if(root==='tickets')item={id:crypto.randomUUID(),name:'新票种',price:'¥0',gift:'填写特典'};if(root==='highlights')item={id:crypto.randomUUID(),title:'新企划',text:'填写企划说明'};if(root==='booths')item={id:crypto.randomUUID(),no:'A00',name:'新社团',type:'填写制品类型'};if(root==='schedule')item={id:crypto.randomUUID(),time:'12:00',title:'新节目',stage:'MAIN STAGE'};state[root].push(item);scheduleSave();const i=state[root].length-1;const wrap=document.createElement('div');wrap.innerHTML=root==='tickets'?ticketHtml(item,i):root==='highlights'?highlightHtml(item,i):root==='booths'?boothHtml(item,i):scheduleHtml(item,i);const node=wrap.firstElementChild;button.before(node);node.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>node.querySelector('[data-edit]')?.focus(),250);toast('已添加')}
function duplicateItem(root,i){checkpoint();const copy=structuredClone(state[root][i]);copy.id=crypto.randomUUID();state[root].splice(i+1,0,copy);scheduleSave();rerenderList(root,i+1)}
function moveItem(root,i,d){const j=i+d;if(j<0||j>=state[root].length)return;checkpoint();[state[root][i],state[root][j]]=[state[root][j],state[root][i]];scheduleSave();rerenderList(root,j)}
function deleteItem(root,i){if(!confirm('删除这个条目？'))return;checkpoint();state[root].splice(i,1);scheduleSave();rerenderList(root);inspector.innerHTML='<div class="inspector-empty"><b>已删除</b></div>'}
function rerenderList(root,focusIndex){const map={tickets:['ticketList',ticketHtml],highlights:['highlightList',highlightHtml],booths:['boothList',boothHtml],schedule:['scheduleList',scheduleHtml]};const [id,fn]=map[root];const list=canvas.querySelector('#'+id);const add=list.querySelector('[data-add]');[...list.querySelectorAll('[data-item]')].forEach(x=>x.remove());state[root].forEach((x,i)=>{const wrap=document.createElement('div');wrap.innerHTML=fn(x,i);list.insertBefore(wrap.firstElementChild,add)});if(Number.isInteger(focusIndex))list.querySelector(`[data-item="${root}.${focusIndex}"]`)?.scrollIntoView({block:'center'})}
$('#imageInput').addEventListener('change',e=>{const file=e.target.files?.[0];const path=e.target.dataset.path;e.target.value='';if(!file||!path)return;checkpoint();const r=new FileReader();r.onload=()=>{setDeep(path,r.result);const el=canvas.querySelector(`[data-image="${CSS.escape(path)}"]`);if(el)el.style.backgroundImage=`linear-gradient(180deg,transparent,#0004),url("${r.result}")`;toast('图片已替换')};r.readAsDataURL(file)})
$('#deviceBtn').onclick=()=>{canvas.classList.toggle('mobile');$('#deviceBtn').textContent=canvas.classList.contains('mobile')?'桌面':'手机'}
$('#previewBtn').onclick=()=>{preview=!preview;$('#previewBtn').textContent=preview?'继续编辑':'预览';syncPreviewClass();toast(preview?'现在看到的是发布效果':'已返回编辑')}
$('.page-nav').addEventListener('click',e=>{const b=e.target.closest('[data-jump]');if(!b)return;canvas.querySelector('#'+b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'})})
$('#undoBtn').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(state));state=JSON.parse(history.pop());mount();scheduleSave();syncHistory()}
$('#redoBtn').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(state));state=JSON.parse(future.pop());mount();scheduleSave();syncHistory()}
$('#publishBtn').onclick=()=>{const html='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'+canvas.innerHTML;const blob=new Blob([html],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='onlyevent-01.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已导出 HTML')}
mount();syncHistory();